name: Feature request
description: Suggest an improvement
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement.
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe your preferred approach
      placeholder: I would like `wtf` to...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Any alternatives or workarounds you've considered
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Links, examples, screenshots, related tools
